#action.yml
name: 'Custom Github Action'
description: 'GA takes inputs and returns outputs'
inputs:
  num:
    required: true
    default: "1"
outputs:
  num_spuared:
    value: ${{ steps.get-square.outputs.num_squared }}
runs:
  using: 'composite'
  steps:
    - name: Intsall Python
      uses: actions/stepup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Pass inputs to Shell
      run: |
        echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
    - name: Fetch the number' square
      id: get-square
      run: python src/get_num_square.py
      shell: bash
